# Generated by Django 4.1.1 on 2024-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_doctordrag_total_price_drag_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordrag",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
