# Generated by Django 4.1.1 on 2024-05-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_doctordrag_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="drag",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="drag",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dragcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
