# Generated by Django 4.1.1 on 2024-05-28 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_dailyspend_doctor_total_money_paid_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctordrag",
            unique_together={("doctor", "drag")},
        ),
    ]
