# Generated by Django 4.1.1 on 2024-05-29 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_doctordrag_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctordrag",
            unique_together=set(),
        ),
    ]
